name: vmcli
executables:
  vmcli:
    source-dirs: src
    main: Main.hs

tests:
  spec:
    source-dirs: [spec, src]
    main: Spec.hs
    dependencies:
      - hspec
      - hspec-discover
      - hspec-golden
      - mockery
      - silently
      - temporary

ghc-options:
  - -O0
  - -threaded
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-name-shadowing
  - -Wno-partial-fields
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe
  - -Wno-unused-packages

default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - ViewPatterns

dependencies:
  - aeson
  - base
  - bytestring
  - containers
  - cradle
  - directory
  - filelock
  - filepath
  - generic-lens
  - interpolate
  - lens
  - optparse-applicative
  - port-utils
  - process
  - safe-exceptions
  - string-conversions
  - strip-ansi-escape
  - text
  - unix
  - xdg-basedir
